@startuml

hide footbox

autonumber

skinparam sequence {
    ParticipantBorderColor grey
    ParticipantBackgroundColor #EFEFEF
    ParticipantFontName Futura
    ParticipantFontSize 15

    ActorBackgroundColor #EFEFEF
    ActorBorderColor black

    ArrowFontName Futura
}

actor User
participant "__:PreferencesActivity__"
participant "__:PreferencesFacade__"
participant "__:SharedPreferences.Editor__"


activate User
User -> "__:PreferencesActivity__": saveSettings()
activate "__:PreferencesActivity__"
alt arePreferencesFilled() == true
    "__:PreferencesActivity__" -> "__:PreferencesFacade__": getInstance(context)
    activate "__:PreferencesFacade__"
    "__:PreferencesFacade__" --> "__:PreferencesActivity__": instance
    "__:PreferencesActivity__" -> "__:PreferencesFacade__":saveServerURL(serverURL)
    "__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": putString(serverUrl)
    activate "__:SharedPreferences.Editor__"
    "__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": apply()

    "__:PreferencesActivity__" -> "__:PreferencesFacade__":savePassword(password)
    "__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": putString(password)
"__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": apply()
    "__:PreferencesActivity__" -> "__:PreferencesFacade__":saveUserName(username)
    "__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": putString(username)
"__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": apply()
    "__:PreferencesActivity__" -> "__:PreferencesFacade__":saveExchangeURL(exchangeURL)
    "__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": putString(exchangeURL)
"__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": apply()
    "__:PreferencesActivity__" -> "__:PreferencesFacade__":saveExchangeUser(exchangeUsername)
    "__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": putString(exchangeUsername)
"__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": apply()
    "__:PreferencesActivity__" -> "__:PreferencesFacade__":saveExchangePassword(exchangePassword)
    "__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": putString(exchangePassword)
"__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": apply()
    "__:PreferencesActivity__" -> "__:PreferencesFacade__":saveMovementDetectionOn(movementDetection)
    "__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": putBoolean(movementDetection)
"__:PreferencesFacade__" -> "__:SharedPreferences.Editor__": apply()
    "__:PreferencesActivity__" -> "__:PreferencesActivity__": finish()
    deactivate "__:SharedPreferences.Editor__"
    deactivate "__:PreferencesFacade__"


else arePreferencesFilled() == false
    "__:PreferencesActivity__" -> "__:PreferencesActivity__":showToast()

end

"__:PreferencesActivity__" --> User: view




@enduml