@startuml

hide footbox

autonumber

skinparam sequence {
    ParticipantBorderColor grey
    ParticipantBackgroundColor #EFEFEF
    ParticipantFontName Futura
    ParticipantFontSize 15

    ActorBackgroundColor #EFEFEF
    ActorBorderColor black

    ArrowFontName Futura
}

actor User
participant "__:MainMenuItem__"
participant "__:BasicMenuItem__"
participant "__:Context__"
participant "__:PreferencesFacade__"
participant "__:IssuesActivity__"
participant "__:GetIssuesTask__"
participant "__:BugzillaAsyncTask__"
participant "__:Gson__"

activate User
User -> "__:MainMenuItem__":onClick(this)
activate "__:MainMenuItem__"
"__:MainMenuItem__" -> "__:BasicMenuItem__":onClick(context)
activate "__:BasicMenuItem__"
"__:BasicMenuItem__" -> "__:MainMenuItem__":getIntentFromPosition(position)
"__:MainMenuItem__" -> "__:PreferencesFacade__":getInstance(context)
activate "__:PreferencesFacade__"
"__:PreferencesFacade__" --> "__:MainMenuItem__": instance
"__:MainMenuItem__" -> "__:PreferencesFacade__": getUserName()
"__:PreferencesFacade__" --> "__:MainMenuItem__": username
"__:MainMenuItem__" --> "__:BasicMenuItem__":intent
 deactivate "__:MainMenuItem__"

 "__:BasicMenuItem__" -> "__:Context__":startActivity(intent)
 deactivate "__:BasicMenuItem__"

 activate "__:Context__"
 "__:Context__" -> "__:IssuesActivity__":onCreate()
 deactivate "__:Context__"
 activate "__:IssuesActivity__"
 "__:IssuesActivity__" -> "__:PreferencesFacade__":getServerURL()
 "__:PreferencesFacade__" --> "__:IssuesActivity__":serverURL
 deactivate "__:PreferencesFacade__"
 "__:IssuesActivity__" -> "__:GetIssuesTask__": new GetIssuesTask(this, username, serverURL, this)
 activate "__:GetIssuesTask__"
 "__:GetIssuesTask__" --> "__:IssuesActivity__":instance
 "__:IssuesActivity__" -> "__:GetIssuesTask__":setAsyncDelegate(this)
 "__:IssuesActivity__" -> "__:GetIssuesTask__":execute()
 "__:GetIssuesTask__" ->> "__:BugzillaAsyncTask__":callRestService(serverURL)
 activate "__:BugzillaAsyncTask__"
 "__:BugzillaAsyncTask__" -->> "__:GetIssuesTask__":result
 deactivate "__:BugzillaAsyncTask__"
 "__:GetIssuesTask__" ->> "__:IssuesActivity__":onPostExecuteFinished(result)
 deactivate "__:GetIssuesTask__"
 "__:IssuesActivity__" -> "__:Gson__":fromJson(result)
 activate "__:Gson__"
 "__:Gson__" --> "__:IssuesActivity__": issues
 deactivate "__:Gson__"
 "__:IssuesActivity__" -> "__:IssuesActivity__":refreshAdapter()
 "__:IssuesActivity__" --> User:view





@enduml